In [2]:
import torch
import torch.nn as nn

bce_loss = nn.BCELoss()
sigmoid = nn.Sigmoid()

probabilities = sigmoid(torch.randn(4, 1, requires_grad=True))
targets = torch.tensor([1, 0, 1, 0], dtype=torch.float32).view(4, 1)

loss = bce_loss(probabilities, targets)

print(probabilities)
print(loss)


tensor([[0.4397],
        [0.5171],
        [0.2600],
        [0.4331]], grad_fn=<SigmoidBackward0>)
tensor(0.8660, grad_fn=<BinaryCrossEntropyBackward0>)


In [3]:
import torch 
from torchvision.models import resnet18, ResNet18_Weights

model = resnet18(weights=ResNet18_Weights.DEFAULT)

data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

prediction = model(data)

loss = (prediction - labels).sum()
loss.backward()

optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

optim.step()


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\ykoon/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 57.2MB/s]


In [6]:
print(loss)

tensor(-473.8115, grad_fn=<SumBackward0>)


In [9]:
prediction

tensor([[-7.6682e-01, -5.4219e-01, -8.7980e-01, -1.7875e+00, -7.1013e-01,
         -4.4376e-01, -8.6794e-01,  7.5910e-01,  5.1992e-01, -5.2989e-01,
         -9.3841e-01, -9.0924e-01, -2.7156e-01, -9.6996e-01, -1.0714e+00,
         -5.6206e-01, -1.0217e+00, -5.2994e-01, -3.7998e-01, -7.1111e-01,
         -1.6300e+00, -8.7752e-01, -1.6120e+00,  1.7932e-01, -1.2480e+00,
         -1.2268e+00, -8.0364e-01, -1.4093e+00, -1.0119e+00, -2.5184e-01,
         -9.4070e-01, -9.9181e-01, -5.6302e-01, -1.1532e+00, -7.1430e-01,
         -6.7650e-01,  2.2413e-01, -1.0443e+00, -6.5575e-01,  4.1359e-02,
         -7.9920e-01, -8.5697e-01, -1.1123e+00, -7.1337e-01, -7.4033e-01,
         -5.0267e-01, -8.1242e-01, -6.8513e-01, -1.3215e+00, -1.2567e+00,
         -7.9639e-01, -1.0699e-01, -5.6514e-01, -9.5839e-01, -3.3163e-01,
         -1.4451e+00, -3.6973e-01, -1.6315e+00, -7.3932e-01, -7.5398e-01,
          7.0058e-01,  1.7217e-01, -1.4759e-01,  8.3694e-02, -9.8578e-01,
         -4.0551e-01, -3.4846e-01, -5.

In [1]:
import torch 

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2

external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

print(9*a**2 == a.grad)
print(-2*b == b.grad)


tensor([True, True])
tensor([True, True])


Temperature : 무작위성. 창의적으로 만들려면 0.9, 답이 있을 경우 0을 권장. Top P 와 동시에 변경하는 것은 권장하지 않음. (기본값: 0.7 ~ 0.2)

Top P : Nucleus 샘플링. 선택 확률 값6이 높은 토큰을 순서대로 나열한 후 설정한 누적 확률 값에 포함되지 않은 토큰을 제거할 때 사용하는 기준값. 0.1은 상위 10%의 확률을 가진 토큰으로부터 샘플링한다는 의미. 